### ISSUE TITLE
Plugin not found

### ISSUE THREAD

**Issue by flyasky** [tomasbjerre/violation-comments-to-gitlab-maven-plugin#2]
mvn violation-comments-to-gitlab-maven-plugin:violation-comments -DGITLAB_URL=https://git.../ -DGITLAB_MERGEREQUESTIID=590 -DGITLAB_PROJECTID=121 -DGITLAB_APITOKEN=HXwo...

[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 1.088 s
[INFO] Finished at: 2018-09-22T17:01:47+03:00
[INFO] Final Memory: 11M/203M
[INFO] ------------------------------------------------------------------------
[ERROR] No plugin found for prefix 'violation-comments-to-gitlab-maven-plugin' in the current project and in the plugin groups [org.apache.maven.plugins, org.codehaus.mojo] available from the repositories [local (/home/aburkun/.m2/repository), central (https://repo.maven.apache.org/maven2)] -> [Help 1]

Can be fixed with ~/.m2/settings.xml with 

                <settings>
                   <pluginGroups>
                      <pluginGroup>se.bjurr.violations</pluginGroup>
                   </pluginGroups>
                </settings>

But expected to work without this config.

**Comment by tomasbjerre** [comment]
Really? Should you not have the group in the command? Like `mvn se.bjurr.violations:violation-comments-to-gitlab-maven-plugin:violation-comments -DGITLAB_URL=https://git.../ -DGITLAB_MERGEREQUESTIID=590 -DGITLAB_PROJECTID=121 -DGITLAB_APITOKEN=HXwo...`

**Comment by tomasbjerre** [comment]
Actually, you command works fine for me with Maven 3.5.2.

Have a look at the [`build.sh`](violation-comments-to-gitlab-maven-plugin:violation-comments) in the root of this repo.

**Comment by atmcarmo** [comment]
Maven plugin prefix resolution by default only works with `org.apache.maven.plugins`.

Source: https://maven.apache.org/guides/introduction/introduction-to-plugin-prefix-mapping.html

There are instructions to add more plugin groups.

So this is not an issue of this plugin.
