### ISSUE TITLE
Problem to run plugin on gitlab CI

### ISSUE THREAD

**Issue by flyasky** [tomasbjerre/violation-comments-to-gitlab-maven-plugin#4]
`[ERROR] Failed to execute goal se.bjurr.violations:violation-comments-to-gitlab-maven-plugin:1.26:violation-comments (default-cli) on project SmartTube: Execution default-cli of goal se.bjurr.violations:violation-comments-to-gitlab-maven-plugin:1.26:violation-comments failed: Plugin se.bjurr.violations:violation-comments-to-gitlab-maven-plugin:1.26 or one of its dependencies could not be resolved: Failed to collect dependencies at se.bjurr.violations:violation-comments-to-gitlab-maven-plugin:jar:1.26 -> se.bjurr.violations:violation-comments-to-gitlab-lib:jar:1.55 -> com.github.tomasbjerre:java-gitlab-api:jar:comment-on-diff-2: Failed to read artifact descriptor for com.github.tomasbjerre:java-gitlab-api:jar:comment-on-diff-2: Could not transfer artifact com.github.tomasbjerre:java-gitlab-api:pom:comment-on-diff-2 from/to jitpack.io (https://jitpack.io): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]`

**Comment by tomasbjerre** [comment]
Jitpack is used because https://github.com/timols/java-gitlab-api is very slow at correcting bugs.

And this is not a problem with the plugin:
```
(https://jitpack.io): sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target -> [Help 1]
```

**Comment by tomasbjerre** [comment]
1.28 now uses gitlab4j-api from Maven Central. No need for Jitpack.
