### ISSUE TITLE
How to avoid comments on white lines in gitlab diff?

### ISSUE THREAD

**Issue by flyasky** [tomasbjerre/violation-comments-to-gitlab-maven-plugin#6]
Hello! We got many comments on "white" lines in diff. Is it possible to switch this off?

**Comment by tomasbjerre** [comment]
I'm guessing your issue is same as https://github.com/jenkinsci/violation-comments-to-gitlab-plugin/issues/19

**Comment by flyasky** [comment]
yes, you're right!

**Comment by tomasbjerre** [comment]
Fixed by @ateglas in https://github.com/tomasbjerre/violation-comments-to-gitlab-maven-plugin/pull/9
